[package]
name = "abstract_chearmyp_boundary"
version = "0.2.0-dev"
authors = ["Kenneth Trecy Tobias <web.kennethtobias@gmail.com>"]
edition = "2021"

[features]
default = []
no_std = []
range_boundary = []
vec_boundary_collection = []
