[package]
name = "abstract_chearmyp_boundary"
version = "1.0.0"
authors = ["Kenneth Trecy Tobias <web.kennethtobias@gmail.com>"]
edition = "2021"
license = "MIT"

[features]
default = []
no_std = []
range_boundary = []
vec_boundary_collection = []
